export default {
  FETCH_FAVOURITE_SHOWS_PENDING: 'FETCH_FAVOURITE_SHOWS_PENDING',
  FETCH_FAVOURITE_SHOWS_SUCCESS: 'FETCH_FAVOURITE_SHOWS_SUCCESS',
  FETCH_FAVOURITE_SHOWS_ERROR: 'FETCH_FAVOURITE_SHOWS_ERROR',
};
