export default {
  FETCH_FAVOURITES: 'FETCH_FAVOURITES',
  FETCH_FAVOURITES_PENDING: 'FETCH_FAVOURITES_PENDING',
  FETCH_FAVOURITES_SUCCESS: 'FETCH_FAVOURITES_SUCCESS',
  FETCH_FAVOURITES_FAILED: 'FETCH_FAVOURITES_FAILED',
  SAVE_FAVOURITES: 'SAVE_FAVOURITES',
};
