export default {
  FETCH_FAVOURITE_SHOWS_PENDING: 'FETCH_FAVOURITE_SHOWS_PENDING',
  FETCH_FAVOURITE_SHOWS_SUCCESS: 'FETCH_FAVOURITE_SHOWS_SUCCESS',
  FETCH_FAVOURITE_SHOWS_FAILED: 'FETCH_FAVOURITE_SHOWS_FAILED',
};
