export default {
  FETCH_SCHEDULE_PENDING: 'FETCH_SCHEDULE_PENDING',
  FETCH_SCHEDULE_SUCCESS: 'FETCH_SCHEDULE_SUCCESS',
  FETCH_SCHEDULE_FAILED: 'FETCH_SCHEDULE_FAILED',
  SET_COUNTRY_FILTER: 'SET_COUNTRY_FILTER',
  SET_CHANNEL_FILTER: 'SET_CHANNEL_FILTER',
};
