export default {
  SET_QUERY: 'SET_QUERY',
  CLEAR_QUERY: 'CLEAR_QUERY',
  FETCH_RESULTS_PENDING: 'FETCH_RESULTS_PENDING',
  FETCH_RESULTS_SUCCESS: 'FETCH_RESULTS_SUCCESS',
  FETCH_RESULTS_FAILED: 'FETCH_RESULTS_FAILED',
};
