export default {
  FETCH_SHOW_PENDING: 'FETCH_SHOW_PENDING',
  FETCH_SHOW_SUCCESS: 'FETCH_SHOW_SUCCESS',
  FETCH_SHOW_FAILED: 'FETCH_SHOW_FAILED',
  FETCH_SHOW_SEASON_AND_EPISODES_PENDING: 'FETCH_SHOW_SEASON_AND_EPISODES_PENDING',
  FETCH_SHOW_SEASON_AND_EPISODES_SUCCESS: 'FETCH_SHOW_SEASON_AND_EPISODES_SUCCESS',
  FETCH_SHOW_SEASON_AND_EPISODES_FAILED: 'FETCH_SHOW_SEASON_AND_EPISODES_FAILED',
};
